### PR TITLE
Add a LICENSE.txt file

### PR DESCRIPTION
**Pull request by sammy-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/lcmtypes/9)

### CODE REVIEW

**Comment by sammy-tri** [comment]
Fixes #2

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[LICENSE.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9#-KaxzqTEx0Yvewd4_amh:-KaxzqTEx0Yvewd4_ami:b-nydov4) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/e90589707fb5558c28bd2b1229a3f99b0e442725/LICENSE.txt#L10)):*
> ```
> Copyright 2016 Wolfgang Merkt
> Copyright 2016 University of Edinburgh
> Copyright 2016-2017 Robot Locomotion Group @ CSAIL
> ```

BTW I will let @mwoehlke-kitware check this list against the data he collected.  It seems approximately correct.  Please positively ACK for me that it's exactly correct?

---

*[LICENSE.txt, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9#-Kaxzgkgw5wb40she_h3:-KaxzgkhRvXFjIBzXrQE:bvm2fma) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/e90589707fb5558c28bd2b1229a3f99b0e442725/LICENSE.txt#L23)):*
> ```
> conditions and the following disclaimer in the documentation and/or
> other materials provided with the distribution.  Neither the name of
> the Massachusetts Institute of Technology nor the names of its
> ```

s/M..I..T../copyright holder/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9#-:-Kay-7Bd2s3I4hZ1Vb3w:bnfp4nl)*

**Comment by sammy-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[LICENSE.txt, line 23 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9#-Kaxzgkgw5wb40she_h3:-Kay-bLARCyqmfvHLJLi:b-896fix) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/e90589707fb5558c28bd2b1229a3f99b0e442725/LICENSE.txt#L23)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

s/M..I..T../copyright holder/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9)*

**Comment by mwoehlke-kitware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[LICENSE.txt, line 10 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9#-KaxzqTEx0Yvewd4_amh:-KbR5O3EVxhT-rG_78Gi:b-u3qlkh) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/e90589707fb5558c28bd2b1229a3f99b0e442725/LICENSE.txt#L10)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I will let @mwoehlke-kitware check this list against the data he collected.  It seems approximately correct.  Please positively ACK for me that it's exactly correct?
</blockquote></details>

:+1:

BTW/FWIW, I've gotten out of the habit of listing all copyright years (that's what history is for); the other attributions are presumed accurate only as a record of most recent contribution. (IOW, I would consider making the last one just 2017...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9)*

**Comment by mwoehlke-kitware** [comment]
:lgtm:

Pedantically speaking, the "approved" license is https://opensource.org/licenses/BSD-3-Clause. I guess the formatting doesn't matter (though that version is "prettier"). I do note FTR that the "name of the copyright holder" stuff was fixed from the earlier revision that still specified "MIT" :+1:.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/9#-:-KbR6RvswsUK2H72ZQDO:b-49ogv8)*

**Pull request merged**
