### PR TITLE
Add LCM types for point, quaternion, pose, header and pose_stamped

### PR DESCRIPTION
**Pull request by kunimatsu-tri**
Based-on the [discussion](https://github.com/RobotLocomotion/drake/pull/6155), I'm putting these lcmtypes here.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/lcmtypes/12)

### CODE REVIEW

**Comment by kunimatsu-tri** [comment]
cc @patmarion @manuelli @RussTedrake and @naveenoid.

**Comment by sammy-tri** [comment]
:lgtm: Once you've decided you've had sufficient review to merge, go ahead (or let me know if you have some problems and need a manual merge)

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/12#-:-KkqsWKIZTz2OyVhDdV5:boobmfj)*

**Comment by kunimatsu-tri** [comment]
@sammy-tri: Got it. Thanks for the review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/12#-:-Kkqt-yUqIoaOTQMOqJf:bxbv79a)*

**Comment by siyuanfeng-tri** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/12#-:-Kkul-oNC4jfwjZeRIYw:bnfp4nl)*

**Pull request merged**
