### PR TITLE
Update project identity

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Rename CMake project, LCM types, build artifacts, etc. to match our new identity. Critically, this changes:
- The name one searches for in order to use the project, whether via CMake `find_package` or `pkgconfig`.
- The package name of the LCM types (also affecting the C/C++ header names and Python names).
- The name of the library as given to CMake `target_link_libraries`.

The name of the lcmspy plugin is also updated. Incidentally, interface include directories for the build tree were missing and have been added. This also applies the recent change from Drake that the interface include directories should reflect not using `lcmtypes/` in the `#include` directives.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/lcmtypes/1)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
@sammy-tri for feature review, @jwnimmer-tri for platform review (unless you have better suspects, in which case feel free to pass the buck)

**Comment by sammy-tri** [comment]
:lgtm:

---

Reviewed 88 of 88 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/1#-:-KSquAFJHFAjPwdIX9F5:bnfp4nl)_

**Comment by jwnimmer-tri** [comment]
:lgtm:  Please be sure a grep -i for `bot2` comes up clean (or at least only sensible mentions) before merging.

---

Reviewed 88 of 88 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/1#-:-KSr0yRqW-j-Wprfm7Bw:b-bdxt05)_

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/1)_

**Comment by mwoehlke-kitware** [comment]
> Please be sure a grep -i for `bot2` comes up clean

Good point. I was doing that to some extent already, but missed the `README.md`.

Even better:

```
$ git grep -iP '(?<!ro|shib)bot(?!loco|tom|h)'
lcmtypes/utime_t.lcm:4:// for bot_timestamp_now() as gazebo creates its own non-uniform clock
```

...which catches "libbot", "bot_core", "bot2", etc. Gotta love PCRE's :grin:.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/1#-:-KSr3r55lkrTqYr2bWX3:b-gbryz2)_

**Pull request merged**
