### PR TITLE
add viewer2_comms_t message

### PR DESCRIPTION
**Pull request by patmarion**
original author @rdeits

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/lcmtypes/8)

### CODE REVIEW

**Comment by rdeits** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-:-Kaxp-4HQWc9B9spuBjx:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-:-KaxpRy84GWB2gmTokIU:bnfp4nl)*

**Comment by liangfok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[lcmtypes/viewer2_comms_t.lcm, line 3 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-Kaxsi-Svhw3YP6-uCZp:-Kaxsi-Svhw3YP6-uCZq:b-6sqkd7) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/16fde969e0c6a6e19d0f5ed75d352701082378f2/lcmtypes/viewer2_comms_t.lcm#L3)):*
> ```
> package robotlocomotion;
> 
> struct viewer2_comms_t
> ```

BTW, consider adding a brief description of what this message is for and how it is expected to be used.

---

*[lcmtypes/viewer2_comms_t.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-KaxsZ1U2Hp839mx_bno:-KaxsZ1U2Hp839mx_bnp:bym71t4) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/16fde969e0c6a6e19d0f5ed75d352701082378f2/lcmtypes/viewer2_comms_t.lcm#L5)):*
> ```
> struct viewer2_comms_t
> {
>   // The timestamp in microseconds
> ```

BTW: nit: missing period at end of sentence.

---

*[lcmtypes/viewer2_comms_t.lcm, line 14 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-KaxsdMrh9Sy6sONwEzN:-KaxsdMrh9Sy6sONwEzO:bym71t4) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/16fde969e0c6a6e19d0f5ed75d352701082378f2/lcmtypes/viewer2_comms_t.lcm#L14)):*
> ```
>   int32_t format_version_minor;
> 
>   // The viewer data
> ```

BTW: nit: missing period at end of sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8)*

**Comment by jwnimmer-tri** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lcmtypes/viewer2_comms_t.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-KaxsZ1U2Hp839mx_bno:-KaxtKA3VNTDU6hhA-vA:b-v6khas) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/16fde969e0c6a6e19d0f5ed75d352701082378f2/lcmtypes/viewer2_comms_t.lcm#L5)):*
<details><summary><i>Previously, liangfok (Chien-Liang Fok) wrote…</i></summary><blockquote>

BTW: nit: missing period at end of sentence.
</blockquote></details>

It is not a sentence!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8)*

**Comment by liangfok** [comment]
*[lcmtypes/viewer2_comms_t.lcm, line 5 at r1](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8#-KaxsZ1U2Hp839mx_bno:-Kay6AgSfeTUZRCn8G-o:bsq91dn) ([raw file](https://github.com/robotlocomotion/lcmtypes/blob/16fde969e0c6a6e19d0f5ed75d352701082378f2/lcmtypes/viewer2_comms_t.lcm#L5)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is not a sentence!
</blockquote></details>

BTW, consider making it a sentence. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/lcmtypes/8)*

**Pull request merged**
